# Generated by Django 5.0.6 on 2024-05-13 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='blog_details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=155)),
                ('blog_msg', models.TextField()),
                ('blog_link', models.EmailField(max_length=254)),
            ],
        ),
    ]
