# Generated by Django 5.0.6 on 2024-05-13 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_blog_details'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog_details',
            name='blog_link',
            field=models.CharField(max_length=155),
        ),
    ]
